server:
  port: 59020

spring:
  application:
    name: toy-server

  datasource:
    url: jdbc:mariadb://localhost:59010/app_server
    username: miv
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect